### ISSUE TITLE
播放完视频广告后报错，非常多次数没有计算收益

### ISSUE THREAD

**Issue by ahyangnb** [OpenFlutter/Pangolin#49]
每次播放完视频激励广告都报错，经过测试，非常多次播放没有计算到收益。

使用插件版本：0.2.3
```
D/EgretLoader(17840): EgretLoader(Context context)
D/EgretLoader(17840): The context is not activity
W/cr_AwContents(17840): Application attempted to call on a destroyed WebView
W/cr_AwContents(17840): java.lang.Throwable
W/cr_AwContents(17840): 	at org.chromium.android_webview.AwContents.f(PG:379)
W/cr_AwContents(17840): 	at org.chromium.android_webview.AwContents.a(PG:353)
W/cr_AwContents(17840): 	at org.chromium.android_webview.AwContents.b(PG:439)
W/cr_AwContents(17840): 	at com.android.webview.chromium.WebViewChromium.loadUrl(PG:251)
W/cr_AwContents(17840): 	at android.webkit.WebView.loadUrl(WebView.java:720)
W/cr_AwContents(17840): 	at com.bytedance.sdk.openadsdk.core.widget.webview.SSWebView.loadUrl(SSWebView.java:93)
W/cr_AwContents(17840): 	at com.bytedance.sdk.openadsdk.core.widget.webview.d.a(WebViewPool.java:131)
W/cr_AwContents(17840): 	at com.bytedance.sdk.openadsdk.core.nativeexpress.NativeExpressView.q(NativeExpressView.java:622)
W/cr_AwContents(17840): 	at com.bytedance.sdk.openadsdk.core.nativeexpress.NativeExpressView.onDetachedFromWindow(NativeExpressView.java:693)
W/cr_AwContents(17840): 	at android.view.View.dispatchDetachedFromWindow(View.java:18437)
W/cr_AwContents(17840): 	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3779)
W/cr_AwContents(17840): 	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5363)
W/cr_AwContents(17840): 	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5334)
W/cr_AwContents(17840): 	at android.view.ViewGroup.removeView(ViewGroup.java:5265)
W/cr_AwContents(17840): 	at com.bytedance.sdk.openadsdk.core.nativeexpress.NativeExpressView.k(NativeExpressView.java:665)
W/cr_AwContents(17840): 	at com.bytedance.sdk.openadsdk.activity.base.TTRewardExpressVideoActivity.onDestroy(TTRewardExpressVideoActivity.java:485)
W/cr_AwContents(17840): 	at android.app.Activity.performDestroy(Activity.java:7532)
W/cr_AwContents(17840): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1307)
W/cr_AwContents(17840): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4562)
W/cr_AwContents(17840): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4596)
W/cr_AwContents(17840): 	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:39)
W/cr_AwContents(17840): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
W/cr_AwContents(17840): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
W/cr_AwContents(17840): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1847)
W/cr_AwContents(17840): 	at android.os.Handler.dispatchMessage(Handler.java:106)
W/cr_AwContents(17840): 	at android.os.Looper.loop(Looper.java:207)
W/cr_AwContents(17840): 	at android.app.ActivityThread.main(ActivityThread.java:6899)
W/cr_AwContents(17840): 	at java.lang.reflect.Method.invoke(Native Method)
W/cr_AwContents(17840): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
W/cr_AwContents(17840): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
W/cr_AwContents(17840): Application attempted to call on a destroyed WebView
W/cr_AwContents(17840): java.lang.Throwable
W/cr_AwContents(17840): 	at org.chromium.android_webview.AwContents.f(PG:379)
W/cr_AwContents(17840): 	at org.chromium.android_webview.AwContents.a(PG:353)
W/cr_AwContents(17840): 	at com.android.webview.chromium.WebViewChromium.stopLoading(PG:313)
W/cr_AwContents(17840): 	at android.webkit.WebView.stopLoading(WebView.java:899)
W/cr_AwContents(17840): 	at com.bytedance.sdk.openadsdk.core.widget.webview.SSWebView.stopLoading(SSWebView.java:130)
W/cr_AwContents(17840): 	at com.bytedance.sdk.openadsdk.core.widget.webview.d.a(WebViewPool.java:132)
W/cr_AwContents(17840): 	at com.bytedance.sdk.openadsdk.core.nativeexpress.NativeExpressView.q(NativeExpressView.java:622)
W/cr_AwContents(17840): 	at com.bytedance.sdk.openadsdk.core.nativeexpress.NativeExpressView.onDetachedFromWindow(NativeExpressView.java:693)
W/cr_AwContents(17840): 	at android.view.View.dispatchDetachedFromWindow(View.java:18437)
W/cr_AwContents(17840): 	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3779)
W/cr_AwContents(17840): 	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5363)
W/cr_AwContents(17840): 	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5334)
W/cr_AwContents(17840): 	at android.view.ViewGroup.removeView(ViewGroup.java:5265)
W/cr_AwContents(17840): 	at com.bytedance.sdk.openadsdk.core.nativeexpress.NativeExpressView.k(NativeExpressView.java:665)
W/cr_AwContents(17840): 	at com.bytedance.sdk.openadsdk.activity.base.TTRewardExpressVideoActivity.onDestroy(TTRewardExpressVideoActivity.java:485)
W/cr_AwContents(17840): 	at android.app.Activity.performDestroy(Activity.java:7532)
W/cr_AwContents(17840): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1307)
W/cr_AwContents(17840): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4562)
W/cr_AwContents(17840): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4596)
W/cr_AwContents(17840): 	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:39)
W/cr_AwContents(17840): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
W/cr_AwContents(17840): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
W/cr_AwContents(17840): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1847)
W/cr_AwContents(17840): 	at android.os.Handler.dispatchMessage(Handler.java:106)
W/cr_AwContents(17840): 	at android.os.Looper.loop(Looper.java:207)
W/cr_AwContents(17840): 	at android.app.ActivityThread.main(ActivityThread.java:6899)
W/cr_AwContents(17840): 	at java.lang.reflect.Method.invoke(Native Method)
W/cr_AwContents(17840): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
W/cr_AwContents(17840): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
W/cr_AwContents(17840): Application attempted to call on a destroyed WebView
W/cr_AwContents(17840): java.lang.Throwable
W/cr_AwContents(17840): 	at org.chromium.android_webview.AwContents.f(PG:379)
W/cr_AwContents(17840): 	at org.chromium.android_webview.AwContents.a(PG:353)
W/cr_AwContents(17840): 	at org.chromium.android_webview.AwContents.b(PG:644)
W/cr_AwContents(17840): 	at com.android.webview.chromium.WebViewChromium.clearCache(PG:607)
W/cr_AwContents(17840): 	at android.webkit.WebView.clearCache(WebView.java:1393)
W/cr_AwContents(17840): 	at com.bytedance.sdk.openadsdk.core.widget.webview.SSWebView.clearCache(SSWebView.java:241)
W/cr_AwContents(17840): 	at com.bytedance.sdk.openadsdk.core.widget.webview.d.a(WebViewPool.java:135)
W/cr_AwContents(17840): 	at com.bytedance.sdk.openadsdk.core.nativeexpress.NativeExpressView.q(NativeExpressView.java:622)
W/cr_AwContents(17840): 	at com.bytedance.sdk.openadsdk.core.nativeexpress.NativeExpressView.onDetachedFromWindow(NativeExpressView.java:693)
W/cr_AwContents(17840): 	at android.view.View.dispatchDetachedFromWindow(View.java:18437)
W/cr_AwContents(17840): 	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3779)
W/cr_AwContents(17840): 	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5363)
W/cr_AwContents(17840): 	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5334)
W/cr_AwContents(17840): 	at android.view.ViewGroup.removeView(ViewGroup.java:5265)
W/cr_AwContents(17840): 	at com.bytedance.sdk.openadsdk.core.nativeexpress.NativeExpressView.k(NativeExpressView.java:665)
W/cr_AwContents(17840): 	at com.bytedance.sdk.openadsdk.activity.base.TTRewardExpressVideoActivity.onDestroy(TTRewardExpressVideoActivity.java:485)
W/cr_AwContents(17840): 	at android.app.Activity.performDestroy(Activity.java:7532)
W/cr_AwContents(17840): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1307)
W/cr_AwContents(17840): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4562)
W/cr_AwContents(17840): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4596)
W/cr_AwContents(17840): 	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:39)
W/cr_AwContents(17840): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
W/cr_AwContents(17840): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
W/cr_AwContents(17840): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1847)
W/cr_AwContents(17840): 	at android.os.Handler.dispatchMessage(Handler.java:106)
W/cr_AwContents(17840): 	at android.os.Looper.loop(Looper.java:207)
W/cr_AwContents(17840): 	at android.app.ActivityThread.main(ActivityThread.java:6899)
W/cr_AwContents(17840): 	at java.lang.reflect.Method.invoke(Native Method)
W/cr_AwContents(17840): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
W/cr_AwContents(17840): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
W/cr_AwContents(17840): Application attempted to call on a destroyed WebView
W/cr_AwContents(17840): java.lang.Throwable
W/cr_AwContents(17840): 	at org.chromium.android_webview.AwContents.f(PG:379)
W/cr_AwContents(17840): 	at org.chromium.android_webview.AwContents.a(PG:353)
W/cr_AwContents(17840): 	at com.android.webview.chromium.WebViewChromium.clearHistory(PG:624)
W/cr_AwContents(17840): 	at android.webkit.WebView.clearHistory(WebView.java:1412)
W/cr_AwContents(17840): 	at com.bytedance.sdk.openadsdk.core.widget.webview.SSWebView.clearHistory(SSWebView.java:257)
W/cr_AwContents(17840): 	at com.bytedance.sdk.openadsdk.core.widget.webview.d.a(WebViewPool.java:136)
W/cr_AwContents(17840): 	at com.bytedance.sdk.openadsdk.core.nativeexpress.NativeExpressView.q(NativeExpressView.java:622)
W/cr_AwContents(17840): 	at com.bytedance.sdk.openadsdk.core.nativeexpress.NativeExpressView.onDetachedFromWindow(NativeExpressView.java:693)
W/cr_AwContents(17840): 	at android.view.View.dispatchDetachedFromWindow(View.java:18437)
W/cr_AwContents(17840): 	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3779)
W/cr_AwContents(17840): 	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5363)
W/cr_AwContents(17840): 	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5334)
W/cr_AwContents(17840): 	at android.view.ViewGroup.removeView(ViewGroup.java:5265)
W/cr_AwContents(17840): 	at com.bytedance.sdk.openadsdk.core.nativeexpress.NativeExpressView.k(NativeExpressView.java:665)
W/cr_AwContents(17840): 	at com.bytedance.sdk.openadsdk.activity.base.TTRewardExpressVideoActivity.onDestroy(TTRewardExpressVideoActivity.java:485)
W/cr_AwContents(17840): 	at android.app.Activity.performDestroy(Activity.java:7532)
W/cr_AwContents(17840): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1307)
W/cr_AwContents(17840): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4562)
W/cr_AwContents(17840): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4596)
W/cr_AwContents(17840): 	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:39)
W/cr_AwContents(17840): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
W/cr_AwContents(17840): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
W/cr_AwContents(17840): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1847)
W/cr_AwContents(17840): 	at android.os.Handler.dispatchMessage(Handler.java:106)
W/cr_AwContents(17840): 	at android.os.Looper.loop(Looper.java:207)
W/cr_AwContents(17840): 	at android.app.ActivityThread.main(ActivityThread.java:6899)
W/cr_AwContents(17840): 	at java.lang.reflect.Method.invoke(Native Method)
W/cr_AwContents(17840): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
W/cr_AwContents(17840): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
E/BufferQueueProducer(17840): [SurfaceTexture-0-17840-4] dequeueBuffer: BufferQueue has been abandoned
W/cr_AwContents(17840): Application attempted to call on a destroyed WebView
W/cr_AwContents(17840): java.lang.Throwable
W/cr_AwContents(17840): 	at org.chromium.android_webview.AwContents.f(PG:379)
W/cr_AwContents(17840): 	at org.chromium.android_webview.AwContents.a(PG:353)
W/cr_AwContents(17840): 	at org.chromium.android_webview.AwContents.r(PG:660)
W/cr_AwContents(17840): 	at Bb.loadingStateChanged(PG:139)
W/cr_AwContents(17840): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/cr_AwContents(17840): 	at android.os.MessageQueue.next(MessageQueue.java:332)
W/cr_AwContents(17840): 	at android.os.Looper.loop(Looper.java:168)
W/cr_AwContents(17840): 	at android.app.ActivityThread.main(ActivityThread.java:6899)
W/cr_AwContents(17840): 	at java.lang.reflect.Method.invoke(Native Method)
W/cr_AwContents(17840): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
W/cr_AwContents(17840): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
```

flutter环境：
```
q1deMacBook-Pro:~ q1$ flutter doctor -v
[✓] Flutter (Channel stable, 1.20.2, on macOS 11.0.1 20B50, locale zh-Hans-CN)
    • Flutter version 1.20.2 at /Users/q1/flutter
    • Framework revision bbfbf1770c (4 months ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/q1/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/q1/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] IntelliJ IDEA Community Edition (version 2020.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.52.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • Mi9 Pro 5G (mobile)        • 488d005c                             •
      android-arm64 • Android 9 (API 28)
    • iPhone 12 Pro Max (mobile) • A595C595-65CC-443B-851D-F47E352AE4AE • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)

! Doctor found issues in 2 categories.
```

**Comment by ahyangnb** [comment]
ok
