### ISSUE TITLE
Android激励视频中点击下载下载失败

### ISSUE THREAD

**Issue by huntrist** [OpenFlutter/Pangolin#53]
激励视频中点击下载下载失败
Pangolin v0.2.7
Flutter 1.22.5 stable
Android
必现

测试手机：华为Mate30

点击激励视频中的下载游戏
debug模式下会一直弹出 下载失败，请点击下载区域重新下载

可能关联的报错：
/LibEventLogger(22182): tag embeded_ad
E/LibEventLogger(22182): label ttdownloader_unity
D/DBMultiProviderImpl(22182): query: content://com.jikipedia.app.TTMultiProvider/t_db/ttopensdk.db/template_diff_new
D/DBMultiProviderImpl(22182): update: content://com.jikipedia.app.TTMultiProvider/t_db/ttopensdk.db/template_diff_new
D/DBMultiProviderImpl(22182): query: content://com.jikipedia.app.TTMultiProvider/t_db/ttopensdk.db/template_diff_new
D/AdEventProviderImpl(22182): dispatch event
D/AdEventProviderImpl(22182): dispatch FUN_AD_EVENT_DISPATCH
D/TmplDiffManager(22182): end doCheckAndDeleteTask maxTplCnt,local size500, 目前存储的模版的个数 1
V/DelegateRunnable(22182): run: pool  =  io  waitTime = 0  taskCost =  12  name= saveTemplate
I/AdEvent (22182): tag: rewarded_video_landingpagelabel: ttdownloader_unity 1690912406903831
V/DelegateRunnable(22182): run: pool  =  io  waitTime = 0  taskCost =  19  name= LogTask
W/System.err(22182): android.content.pm.PackageManager$NameNotFoundException: com.oppo.filemanager
W/System.err(22182): 	at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:201)
W/System.err(22182): 	at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:170)
W/System.err(22182): 	at com.ss.android.socialbase.appdownloader.g.b(AppUtils.java:117)
W/System.err(22182): 	at com.ss.android.socialbase.appdownloader.b.b(AhUtils.java:696)
W/System.err(22182): 	at com.ss.android.socialbase.appdownloader.b.a(AhUtils.java:674)
W/System.err(22182): 	at com.ss.android.socialbase.appdownloader.b.a(AhUtils.java:489)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.i.a(DownloadInsideHelper.java:153)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.i.a(DownloadInsideHelper.java:100)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.h.a(DownloadHelper.java:478)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.f.p(CommonDownloadHandler.java:712)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.f.g(CommonDownloadHandler.java:81)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.f$5.a(CommonDownloadHandler.java:702)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.e.a(CleanSpaceHelper.java:73)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.f.o(CommonDownloadHandler.java:696)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.f.b(CommonDownloadHandler.java:690)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.f.f(CommonDownloadHandler.java:600)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.f.e(CommonDownloadHandler.java:488)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.f.c(CommonDownloadHandler.java:454)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.f.b(CommonDownloadHandler.java:357)
/System.err(22182): 	at com.ss.android.downloadlib.f.a(DownloadDispatcher.java:195)
W/System.err(22182): 	at com.ss.android.downloadlib.f.a(DownloadDispatcher.java:178)
W/System.err(22182): 	at com.ss.android.downloadlib.g.a(TTDownloader.java:251)
W/System.err(22182): 	at com.bytedance.sdk.openadsdk.downloadnew.a.d$3.a(DMLibManager.java:521)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.f.s(CommonDownloadHandler.java:887)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.f.f(CommonDownloadHandler.java:593)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.f.e(CommonDownloadHandler.java:488)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.f.c(CommonDownloadHandler.java:454)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.f.b(CommonDownloadHandler.java:357)
W/System.err(22182): 	at com.ss.android.downloadlib.f.a(DownloadDispatcher.java:195)
W/System.err(22182): 	at com.ss.android.downloadlib.g.a(TTDownloader.java:244)
W/System.err(22182): 	at com.bytedance.sdk.openadsdk.downloadnew.a.d.s(DMLibManager.java:510)
W/System.err(22182): 	at com.bytedance.sdk.openadsdk.downloadnew.a.d.e(DMLibManager.java:463)
W/System.err(22182): 	at com.bytedance.sdk.openadsdk.downloadnew.a.d.x(DMLibManager.java:1045)
W/System.err(22182): 	at com.bytedance.sdk.openadsdk.downloadnew.a.d.w(DMLibManager.java:1027)
W/System.err(22182): 	at com.bytedance.sdk.openadsdk.downloadnew.a.d.i(DMLibManager.java:803)
W/System.err(22182): 	at com.bytedance.sdk.openadsdk.downloadnew.a.d.z(DMLibManager.java:1286)
W/System.err(22182): 	at com.bytedance.sdk.openadsdk.downloadnew.a.d.g(DMLibManager.java:594)
W/System.err(22182): 	at com.bytedance.sdk.openadsdk.core.a.a.a(ClickCreativeListener.java:102)
W/System.err(22182): 	at com.bytedance.sdk.openadsdk.activity.base.TTRewardExpressVideoActivity$6.a(TTRewardExpressVideoActivity.java:594)
W/System.err(22182): 	at com.bytedance.sdk.openadsdk.core.nativeexpress.NativeExpressView.a(NativeExpressView.java:787)
W/System.err(22182): 	at com.bytedance.sdk.openadsdk.component.reward.view.FullRewardExpressView.a(FullRewardExpressView.java:203)
W/System.err(22182): 	at com.bytedance.sdk.openadsdk.core.w.k(TTAndroidObject.java:994)
W/System.err(22182): 	at com.bytedance.sdk.openadsdk.core.w.c(TTAndroidObject.java:85)
W/System.err(22182): 	at com.bytedance.sdk.openadsdk.core.w$4.run(TTAndroidObject.java:796)
W/System.err(22182): 	at android.os.Handler.handleCallback(Handler.java:900)
W/System.err(22182): 	at android.os.Handler.dispatchMessage(Handler.java:103)
W/System.err(22182): 	at android.os.Looper.loop(Looper.java:219)
W/System.err(22182): 	at android.app.ActivityThread.main(ActivityThread.java:8387)
/System.err(22182): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(22182): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
W/System.err(22182): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
W/System.err(22182): android.content.pm.PackageManager$NameNotFoundException: com.coloros.filemanager
W/System.err(22182): 	at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:201)
W/System.err(22182): 	at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:170)
W/System.err(22182): 	at com.ss.android.socialbase.appdownloader.g.b(AppUtils.java:117)
W/System.err(22182): 	at com.ss.android.socialbase.appdownloader.b.b(AhUtils.java:696)
W/System.err(22182): 	at com.ss.android.socialbase.appdownloader.b.a(AhUtils.java:674)
W/System.err(22182): 	at com.ss.android.socialbase.appdownloader.b.a(AhUtils.java:489)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.i.a(DownloadInsideHelper.java:153)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.i.a(DownloadInsideHelper.java:100)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.h.a(DownloadHelper.java:478)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.f.p(CommonDownloadHandler.java:712)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.f.g(CommonDownloadHandler.java:81)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.f$5.a(CommonDownloadHandler.java:702)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.e.a(CleanSpaceHelper.java:73)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.f.o(CommonDownloadHandler.java:696)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.f.b(CommonDownloadHandler.java:690)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.f.f(CommonDownloadHandler.java:600)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.f.e(CommonDownloadHandler.java:488)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.f.c(CommonDownloadHandler.java:454)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.f.b(CommonDownloadHandler.java:357)
W/System.err(22182): 	at com.ss.android.downloadlib.f.a(DownloadDispatcher.java:195)
W/System.err(22182): 	at com.ss.android.downloadlib.f.a(DownloadDispatcher.java:178)
W/System.err(22182): 	at com.ss.android.downloadlib.g.a(TTDownloader.java:251)
W/System.err(22182): 	at com.bytedance.sdk.openadsdk.downloadnew.a.d$3.a(DMLibManager.java:521)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.f.s(CommonDownloadHandler.java:887)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.f.f(CommonDownloadHandler.java:593)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.f.e(CommonDownloadHandler.java:488)
/System.err(22182): 	at com.ss.android.downloadlib.addownload.f.c(CommonDownloadHandler.java:454)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.f.b(CommonDownloadHandler.java:357)
W/System.err(22182): 	at com.ss.android.downloadlib.f.a(DownloadDispatcher.java:195)
W/System.err(22182): 	at com.ss.android.downloadlib.g.a(TTDownloader.java:244)
W/System.err(22182): 	at com.bytedance.sdk.openadsdk.downloadnew.a.d.s(DMLibManager.java:510)
W/System.err(22182): 	at com.bytedance.sdk.openadsdk.downloadnew.a.d.e(DMLibManager.java:463)
W/System.err(22182): 	at com.bytedance.sdk.openadsdk.downloadnew.a.d.x(DMLibManager.java:1045)
W/System.err(22182): 	at com.bytedance.sdk.openadsdk.downloadnew.a.d.w(DMLibManager.java:1027)
W/System.err(22182): 	at com.bytedance.sdk.openadsdk.downloadnew.a.d.i(DMLibManager.java:803)
W/System.err(22182): 	at com.bytedance.sdk.openadsdk.downloadnew.a.d.z(DMLibManager.java:1286)
W/System.err(22182): 	at com.bytedance.sdk.openadsdk.downloadnew.a.d.g(DMLibManager.java:594)
W/System.err(22182): 	at com.bytedance.sdk.openadsdk.core.a.a.a(ClickCreativeListener.java:102)
W/System.err(22182): 	at com.bytedance.sdk.openadsdk.activity.base.TTRewardExpressVideoActivity$6.a(TTRewardExpressVideoActivity.java:594)
W/System.err(22182): 	at com.bytedance.sdk.openadsdk.core.nativeexpress.NativeExpressView.a(NativeExpressView.java:787)
W/System.err(22182): 	at com.bytedance.sdk.openadsdk.component.reward.view.FullRewardExpressView.a(FullRewardExpressView.java:203)
W/System.err(22182): 	at com.bytedance.sdk.openadsdk.core.w.k(TTAndroidObject.java:994)
W/System.err(22182): 	at com.bytedance.sdk.openadsdk.core.w.c(TTAndroidObject.java:85)
W/System.err(22182): 	at com.bytedance.sdk.openadsdk.core.w$4.run(TTAndroidObject.java:796)
W/System.err(22182): 	at android.os.Handler.handleCallback(Handler.java:900)
W/System.err(22182): 	at android.os.Handler.dispatchMessage(Handler.java:103)
W/System.err(22182): 	at android.os.Looper.loop(Looper.java:219)
W/System.err(22182): 	at android.app.ActivityThread.main(ActivityThread.java:8387)
W/System.err(22182): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(22182): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
W/System.err(22182): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
W/System.err(22182): android.content.pm.PackageManager$NameNotFoundException: com.android.filemanager
W/System.err(22182): 	at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:201)
W/System.err(22182): 	at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:170)
W/System.err(22182): 	at com.ss.android.socialbase.appdownloader.g.b(AppUtils.java:117)
/System.err(22182): 	at com.ss.android.socialbase.appdownloader.b.b(AhUtils.java:696)
W/System.err(22182): 	at com.ss.android.socialbase.appdownloader.b.a(AhUtils.java:674)
W/System.err(22182): 	at com.ss.android.socialbase.appdownloader.b.a(AhUtils.java:489)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.i.a(DownloadInsideHelper.java:153)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.i.a(DownloadInsideHelper.java:100)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.h.a(DownloadHelper.java:478)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.f.p(CommonDownloadHandler.java:712)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.f.g(CommonDownloadHandler.java:81)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.f$5.a(CommonDownloadHandler.java:702)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.e.a(CleanSpaceHelper.java:73)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.f.o(CommonDownloadHandler.java:696)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.f.b(CommonDownloadHandler.java:690)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.f.f(CommonDownloadHandler.java:600)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.f.e(CommonDownloadHandler.java:488)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.f.c(CommonDownloadHandler.java:454)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.f.b(CommonDownloadHandler.java:357)
W/System.err(22182): 	at com.ss.android.downloadlib.f.a(DownloadDispatcher.java:195)
W/System.err(22182): 	at com.ss.android.downloadlib.f.a(DownloadDispatcher.java:178)
W/System.err(22182): 	at com.ss.android.downloadlib.g.a(TTDownloader.java:251)
W/System.err(22182): 	at com.bytedance.sdk.openadsdk.downloadnew.a.d$3.a(DMLibManager.java:521)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.f.s(CommonDownloadHandler.java:887)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.f.f(CommonDownloadHandler.java:593)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.f.e(CommonDownloadHandler.java:488)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.f.c(CommonDownloadHandler.java:454)
W/System.err(22182): 	at com.ss.android.downloadlib.addownload.f.b(CommonDownloadHandler.java:357)
W/System.err(22182): 	at com.ss.android.downloadlib.f.a(DownloadDispatcher.java:195)
W/System.err(22182): 	at com.ss.android.downloadlib.g.a(TTDownloader.java:244)
W/System.err(22182): 	at com.bytedance.sdk.openadsdk.downloadnew.a.d.s(DMLibManager.java:510)
W/System.err(22182): 	at com.bytedance.sdk.openadsdk.downloadnew.a.d.e(DMLibManager.java:463)
/System.err(22182): 	at com.bytedance.sdk.openadsdk.downloadnew.a.d.x(DMLibManager.java:1045)
W/System.err(22182): 	at com.bytedance.sdk.openadsdk.downloadnew.a.d.w(DMLibManager.java:1027)
W/System.err(22182): 	at com.bytedance.sdk.openadsdk.downloadnew.a.d.i(DMLibManager.java:803)
W/System.err(22182): 	at com.bytedance.sdk.openadsdk.downloadnew.a.d.z(DMLibManager.java:1286)
W/System.err(22182): 	at com.bytedance.sdk.openadsdk.downloadnew.a.d.g(DMLibManager.java:594)
W/System.err(22182): 	at com.bytedance.sdk.openadsdk.core.a.a.a(ClickCreativeListener.java:102)
W/System.err(22182): 	at com.bytedance.sdk.openadsdk.activity.base.TTRewardExpressVideoActivity$6.a(TTRewardExpressVideoActivity.java:594)
W/System.err(22182): 	at com.bytedance.sdk.openadsdk.core.nativeexpress.NativeExpressView.a(NativeExpressView.java:787)
W/System.err(22182): 	at com.bytedance.sdk.openadsdk.component.reward.view.FullRewardExpressView.a(FullRewardExpressView.java:203)
W/System.err(22182): 	at com.bytedance.sdk.openadsdk.core.w.k(TTAndroidObject.java:994)
W/System.err(22182): 	at com.bytedance.sdk.openadsdk.core.w.c(TTAndroidObject.java:85)
W/System.err(22182): 	at com.bytedance.sdk.openadsdk.core.w$4.run(TTAndroidObject.java:796)
W/System.err(22182): 	at android.os.Handler.handleCallback(Handler.java:900)
W/System.err(22182): 	at android.os.Handler.dispatchMessage(Handler.java:103)
W/System.err(22182): 	at android.os.Looper.loop(Looper.java:219)
W/System.err(22182): 	at android.app.ActivityThread.main(ActivityThread.java:8387)
W/System.err(22182): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(22182): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
W/System.err(22182): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
D/DMLibManager(22182): changeDownloadStatus, the current status is2: 2
I/CZL_META(LITE)(22182):
I/CZL_META(LITE)(22182): [22182]    meta(303)
D/FullRewardExpressView(22182): onGetCurrentPlayTime

**Comment by huntrist** [comment]
小米10X，有同样的问题
